alias ssh_prod='ssh -i ~/.ssh/sportq-dev.pem ubuntu@52.66.11.198'
export GOPATH=$HOME/go

# Uncomment the line below to use it as an indication
# that the command 
# $ source ~/.bashrc
# indeed ran.
#PS1='\[\e[1;91m\][\u \w]\$\[\e[0m\] '

export CLICOLOR=1
export LSCOLORS=ExFxBxDxCxegedabagacad
alias ls='ls -GFh'

[[ -s "$HOME/.rvm/scripts/rvm" ]] && source "$HOME/.rvm/scripts/rvm" # Load RVM into a shell session *as a function*
export PATH=$PATH:/usr/local/Cellar/mongodb@3.4/3.4.14/bin/

alias del_swp="find . -name "*.swp" -print -exec rm -i '{}' \;"
# If del_dSYM command gives error - "is a directory"
# add -r flag to rm
alias del_dSYM="find . -name "*.dSYM" -exec rm -i '{}' \;"

# Iterate through parameters skipping the first: `${@:2}`
# See Parameter Expansion in bash manual
#
# 
# Find and delete with function fcd:
# First find and display.
# Wait for confirmation from user.
# Remove with confirmation -i flag (Remove this flag to delete large #files).
# Command format;
# Eg:
#	find . ! \( -name makefile -o -name *.c \) 
#
# `fcd [starting-point] [expression1] [expression2] ... [expressionN]`
fcd () {
  usage="Usage: fcd [starting-point] [expression1] [expression2] ... [expressionN]"
  [[ $# -lt 2 ]] && { echo "$usage"; return 1; }
  for pat in "${@:2}"
  do
	name_str+="-name $pat "
  done;

  find $1 ! \( $name_str\)
  unset usage
}

#xmodmap ~/.xmodmaprc
